# Path to sources
sonar.sources=backend/src/main/java,frontend/src
sonar.exclusions==**/target/**,**/dist/**,**/node_modules/**,**/*.config.js,**/vite.config.ts
#sonar.inclusions=

# Path to tests
sonar.tests=backend/src/test/java

# Source encoding
sonar.sourceEncoding=UTF-8
